openapi: 3.0.0
info:
  title: Bairng API
  description: API for game engine playing Bang the Dice Game.
  version: "0.1.0"
paths:
  /api/test:
    get:
      summary: "Hello World"
      description: "test endpoint"
      operationId: "api.test"
      responses: 
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  content: 
                    type: string
  /api/test_login:
    get:
      summary: "Hello Specific Person"
      description: "test endpoint for logins"
      operationId: "api.test_login"
      responses: 
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  content: 
                    type: string
  /auth/create_user:
    post:
      summary: "Create User"
      description: "Superuser only endpoint for POSTing new users"
      operationId: "auth.create_user"
      responses: 
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  content: 
                    type: application/json